version: '2.4'
services:
  registration-login-demo:
    image: registration-login-demo:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      options:
        max-size: 10m
        max-file: '5'
      driver: json-file
    ports:
      - "8094:8094"
